/* Simulation code for Sattraj.Satellite generated by the OpenModelica Compiler v1.12.0 (64-bit). */
#if !defined(Sattraj_Satellite__MODEL_H)
#define Sattraj_Satellite__MODEL_H
#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "Sattraj.Satellite_functions.h"

#define Sattraj_Vector_index 0

extern void Sattraj_Satellite_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void Sattraj_Satellite_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Sattraj_Satellite_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Sattraj_Satellite_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Sattraj_Satellite_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern int Sattraj_Satellite_checkForDiscreteChanges(DATA *data, threadData_t *threadData);
extern const char* Sattraj_Satellite_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Sattraj_Satellite_relationDescription(int i);
extern void Sattraj_Satellite_function_initSample(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_functionJacG_column(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_functionJacA_column(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_functionJacB_column(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_functionJacC_column(void* data, threadData_t *threadData);
extern int Sattraj_Satellite_functionJacD_column(void* data, threadData_t *threadData);
extern const char* Sattraj_Satellite_linear_model_frame(void);
extern const char* Sattraj_Satellite_linear_model_datarecovery_frame(void);
extern int Sattraj_Satellite_mayer(DATA* data, modelica_real** res, short *);
extern int Sattraj_Satellite_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Sattraj_Satellite_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Sattraj_Satellite_setInputData(DATA *data, const modelica_boolean file);
extern int Sattraj_Satellite_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Sattraj_Satellite_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Sattraj_Satellite_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int Sattraj_Satellite_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void Sattraj_Satellite_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Sattraj_Satellite_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Sattraj_Satellite_inputNames(DATA* data, char ** names);
extern int Sattraj_Satellite_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Sattraj_Satellite_functionLocalKnownVars(DATA*, threadData_t*);
extern int Sattraj_Satellite_symbolicInlineSystem(DATA*, threadData_t*);

#include "Sattraj.Satellite_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#endif

