/* Additional record code for Sattraj.Satellite generated by the OpenModelica Compiler v1.12.0 (64-bit). */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Sattraj_Vector__desc_added 1
const char* Sattraj_Vector__desc__fields[3] = {"x","y","z"};
struct record_description Sattraj_Vector__desc = {
  "Sattraj_Vector", /* package_record__X */
  "Sattraj.Vector", /* package.record_X */
  Sattraj_Vector__desc__fields
};

#ifdef __cplusplus
}
#endif

